version: 2
project_name: multiplayer

builds:
  - main: ./cmd/crew
    binary: crew
    ldflags:
      - -s -w -X github.com/codyhartsook/multiplayer/internal/version.value={{ .Version }}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz
    files:
      - LICENSE
      - README.md

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
