package room

import (
	"fmt"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/codyhartsook/multiplayer/internal/session"
)

// Briefing renders what a session should know on arriving in its rooms.
// Returns "" when there is nothing worth injecting.
func Briefing(rooms []Room, entries []*Entry, others []string, authors Authors) string {
	byRoom := group(entries)
	var b strings.Builder

	for _, r := range rooms {
		live := byRoom[r.Key]
		if len(live) == 0 && len(others) == 0 {
			continue
		}
		fmt.Fprintf(&b, "## crew room: %s (%s)\n\n", r.Name, r.Scope)
		if len(others) > 0 && r.Scope.Local() {
			fmt.Fprintf(&b, "Also here: %s\n\n", strings.Join(others, ", "))
		}
		writeSection(&b, "Notes", live, ModeNote, authors)
		writeOpen(&b, live, authors)
		writeAnswered(&b, live, authors)
	}

	out := strings.TrimSpace(b.String())
	if out == "" {
		return ""
	}
	return out + "\n\n" + hint
}

// Notice is the one-line nudge a turn hook injects: enough to know something is
// waiting, not the content itself. Reading stays the agent's decision.
func Notice(entries []*Entry) string {
	if len(entries) == 0 {
		return ""
	}
	counts := map[Mode]int{}
	answers := 0
	for _, e := range entries {
		switch {
		case e.Resolves != 0:
			answers++
		default:
			counts[e.Mode]++
		}
	}
	var parts []string
	for _, k := range Modes {
		if n := counts[k]; n > 0 {
			parts = append(parts, fmt.Sprintf("%d %s", n, plural(string(k), string(k)+"s", n)))
		}
	}
	if answers > 0 {
		parts = append(parts, fmt.Sprintf("%d %s", answers, plural("answer", "answers", answers)))
	}
	return fmt.Sprintf("crew: %s unread in this room, run `crew room` to read %s.",
		strings.Join(parts, ", "), plural("it", "them", len(entries)))
}

const hint = "Read and acknowledge entries with `crew room`. Post only " +
	"information that changes another agent's work, with " +
	"`crew post <note|request> \"...\"`; " +
	"answer with `crew resolve <id> \"...\"`."

func writeSection(b *strings.Builder, title string, entries []*Entry, mode Mode, authors Authors) {
	var matching []*Entry
	for _, e := range entries {
		if e.Mode == mode {
			matching = append(matching, e)
		}
	}
	if len(matching) == 0 {
		return
	}
	fmt.Fprintf(b, "### %s\n", title)
	for _, e := range matching {
		fmt.Fprintf(b, "- [%d] %s - %s, %s\n", e.ID, oneLine(e.Body), authors.Name(e.Author), Ago(e.CreatedAt))
	}
	b.WriteString("\n")
}

// writeOpen lists what is still waiting.
func writeOpen(b *strings.Builder, entries []*Entry, authors Authors) {
	var open []*Entry
	for _, e := range entries {
		if !e.Open() {
			continue
		}
		open = append(open, e)
	}
	if len(open) == 0 {
		return
	}

	b.WriteString("### Open\n")
	for _, e := range open {
		to := ""
		if e.To != "" {
			to = " to " + authors.Name(e.To)
		}
		fmt.Fprintf(b, "- [%d] %s%s: %s - %s, %s\n", e.ID, e.Mode, to, oneLine(e.Body), authors.Name(e.Author), Ago(e.CreatedAt))
	}
	b.WriteString("\n")
}

// answeredLimit caps how many resolved threads a briefing carries.
const answeredLimit = 5

// writeAnswered shows resolved threads as question and answer. A closed
// question is no longer waiting on anyone, but its answer is exactly the
// context an arriving agent needs.
func writeAnswered(b *strings.Builder, entries []*Entry, authors Authors) {
	byID := map[int64]*Entry{}
	for _, e := range entries {
		byID[e.ID] = e
	}

	var threads []*Entry
	for _, e := range entries {
		if e.Mode.Addressed() && e.Resolves == 0 && e.ResolvedBy != 0 {
			threads = append(threads, e)
		}
	}
	if len(threads) == 0 {
		return
	}
	if len(threads) > answeredLimit {
		threads = threads[len(threads)-answeredLimit:]
	}

	b.WriteString("### Answered\n")
	for _, e := range threads {
		to := ""
		if e.To != "" {
			to = " to " + authors.Name(e.To)
		}
		fmt.Fprintf(b, "- [%d] %s%s: %s\n", e.ID, e.Mode, to, oneLine(e.Body))
		if answer, ok := byID[e.ResolvedBy]; ok {
			fmt.Fprintf(b, "  → %s - %s\n", oneLine(answer.Body), authors.Name(answer.Author))
		}
	}
	b.WriteString("\n")
}

func group(entries []*Entry) map[string][]*Entry {
	byRoom := map[string][]*Entry{}
	for _, e := range entries {
		byRoom[e.Room] = append(byRoom[e.Room], e)
	}
	for _, list := range byRoom {
		sort.Slice(list, func(i, j int) bool { return list[i].ID < list[j].ID })
	}
	return byRoom
}

// Authors maps immutable session keys to friendly aliases.
type Authors map[string]string

// Name renders a friendly alias, falling back to the session key for old data.
func (a Authors) Name(sessionKey string) string {
	if alias := a[sessionKey]; alias != "" {
		return alias
	}
	return Author(sessionKey)
}

// Snapshot renders a room as a read-only Markdown transcript: who is here,
// what it holds, what is still open, then everything posted in order.
func Snapshot(r Room, entries []*Entry, participants, docs []string, authors Authors) string {
	var b strings.Builder
	b.WriteString("<!-- Generated by crew. Changes will be overwritten. -->\n\n")
	fmt.Fprintf(&b, "# %s · %s room\n\n", r.Name, r.Scope)
	fmt.Fprintf(&b, "Room ID: `%s`\n\n", r.Key)
	if len(participants) > 0 {
		b.WriteString("## Participants\n\n")
		for _, participant := range participants {
			fmt.Fprintf(&b, "- %s\n", participant)
		}
		b.WriteString("\n")
	}
	if len(docs) > 0 {
		b.WriteString("## Documents\n\n")
		for _, name := range docs {
			fmt.Fprintf(&b, "- [%s](documents/%s)\n", name, markdownPath(name))
		}
		b.WriteString("\n")
	}
	var open []*Entry
	for _, entry := range entries {
		if entry.Open() {
			open = append(open, entry)
		}
	}
	if len(open) > 0 {
		b.WriteString("## Open requests\n\n")
		for _, entry := range open {
			fmt.Fprintf(&b, "- [#%d](#%d--%s): %s - %s\n", entry.ID, entry.ID, entry.Mode, oneLine(entry.Body), authors.Name(entry.Author))
		}
		b.WriteString("\n")
	}
	b.WriteString("## Timeline\n")
	for _, entry := range entries {
		kind := string(entry.Mode)
		if entry.Resolves != 0 {
			kind = fmt.Sprintf("response to #%d", entry.Resolves)
		}
		fmt.Fprintf(&b, "\n### #%d · %s\n\n", entry.ID, kind)
		fmt.Fprintf(&b, "%s · %s\n\n", authors.Name(entry.Author), entry.CreatedAt.Local().Format("2006-01-02 15:04 MST"))
		b.WriteString(strings.TrimSpace(entry.Body))
		b.WriteString("\n")
	}
	if len(entries) == 0 {
		b.WriteString("\nNothing posted yet.\n")
	}
	return b.String()
}

func markdownPath(path string) string {
	return strings.ReplaceAll(path, " ", "%20")
}

// NameFor names a room from its key alone, for the callers that hold a key
// rather than the place it came from.
func NameFor(key string) string {
	name := filepath.Base(strings.Split(key, "#")[0])
	if name == "." || name == string(filepath.Separator) || name == "" {
		return key
	}
	return name
}

// Participant describes one member of a room in a transcript.
func Participant(s *session.Session) string {
	return fmt.Sprintf("%s - %s", Display(s), s.Status)
}

// Display names a session the way a person reads it: its friendly alias when
// it has one, and the session key otherwise.
func Display(s *session.Session) string {
	if s.Alias != "" {
		return s.Alias
	}
	return Author(s.Key())
}

// Author renders a session key as "harness 8-char-id".
func Author(sessionKey string) string {
	harness, id, ok := strings.Cut(sessionKey, ":")
	if !ok {
		return sessionKey
	}
	if len(id) > 8 {
		id = id[:8]
	}
	return harness + " " + id
}

// Ago renders elapsed time in the largest readable unit.
func Ago(t time.Time) string {
	d := time.Since(t)
	switch {
	case d < time.Minute:
		return "just now"
	case d < time.Hour:
		return fmt.Sprintf("%dm ago", int(d.Minutes()))
	case d < 24*time.Hour:
		return fmt.Sprintf("%dh ago", int(d.Hours()))
	default:
		return fmt.Sprintf("%dd ago", int(d.Hours()/24))
	}
}

func oneLine(s string) string {
	return strings.Join(strings.Fields(s), " ")
}

func plural(one, many string, n int) string {
	if n == 1 {
		return one
	}
	return many
}
