package documentcmd

import (
	"bytes"
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/codyhartsook/multiplayer/internal/cli/cmdutil"
	"github.com/codyhartsook/multiplayer/internal/detect"
	"github.com/codyhartsook/multiplayer/internal/documents"
	"github.com/codyhartsook/multiplayer/internal/harness"
	"github.com/codyhartsook/multiplayer/internal/room"
	"github.com/codyhartsook/multiplayer/internal/session"
	"github.com/codyhartsook/multiplayer/internal/store/sqlitestore"
)

func TestPublishAndOpen(t *testing.T) {
	ctx := context.Background()
	cwd, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	loc, err := detect.New().Detect(ctx, cwd)
	if err != nil {
		t.Fatal(err)
	}
	root := t.TempDir()
	db := filepath.Join(root, "sessions.db")
	st, err := sqlitestore.Open(db)
	if err != nil {
		t.Fatal(err)
	}
	now := time.Now().UTC()
	sess := &session.Session{ID: "docs", Harness: session.HarnessCodex, Status: session.StatusActive, Place: session.Place{CWD: cwd, Repo: loc.Repo}, StartedAt: now, LastSeen: now}
	if err := st.Upsert(ctx, sess); err != nil {
		t.Fatal(err)
	}
	st.Close()
	t.Setenv("CODEX_THREAD_ID", sess.ID)

	source := filepath.Join(t.TempDir(), "plan.md")
	if err := os.WriteFile(source, []byte("# Plan\n\nKeep it simple.\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	opts := &cmdutil.Options{DB: db}
	publish := NewPublish(opts)
	publish.SetArgs([]string{source})
	publish.SetOut(new(bytes.Buffer))
	if err := publish.Execute(); err != nil {
		t.Fatal(err)
	}

	here := room.For(*loc)[0]
	dir, err := documents.Dir(root, here.Key)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, "plan.md")); err != nil {
		t.Fatalf("published document: %v", err)
	}
	open := NewOpen(opts)
	open.SetArgs([]string{"--no-open"})
	open.SetOut(new(bytes.Buffer))
	if err := open.Execute(); err != nil {
		t.Fatal(err)
	}
	snapshot, err := os.ReadFile(filepath.Join(filepath.Dir(dir), "ROOM.md"))
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{"Generated by crew", "[plan.md](documents/plan.md)", "Published document: plan.md"} {
		if !strings.Contains(string(snapshot), want) {
			t.Errorf("ROOM.md missing %q:\n%s", want, snapshot)
		}
	}
}

func TestHumanCanPublishToExplicitRoom(t *testing.T) {
	for _, spec := range harness.Specs() {
		for _, name := range spec.SessionEnv {
			t.Setenv(name, "")
		}
	}
	ctx := context.Background()
	root := t.TempDir()
	db := filepath.Join(root, "sessions.db")
	st, err := sqlitestore.Open(db)
	if err != nil {
		t.Fatal(err)
	}
	foreign := "/src/another-worktree"
	seed := &room.Entry{Room: foreign, Scope: room.ScopeWorktree, Mode: room.ModeNote, Author: "codex:seed", Body: "existing context", CreatedAt: time.Now().UTC()}
	if err := st.Post(ctx, seed); err != nil {
		t.Fatal(err)
	}
	st.Close()

	source := filepath.Join(t.TempDir(), "brief.md")
	if err := os.WriteFile(source, []byte("Human brief"), 0o644); err != nil {
		t.Fatal(err)
	}
	opts := &cmdutil.Options{DB: db}
	publish := NewPublish(opts)
	publish.SetArgs([]string{"--room", foreign, source})
	publish.SetOut(new(bytes.Buffer))
	if err := publish.Execute(); err != nil {
		t.Fatal(err)
	}

	st, err = sqlitestore.Open(db)
	if err != nil {
		t.Fatal(err)
	}
	defer st.Close()
	entries, err := st.Entries(ctx, room.Filter{Rooms: []string{foreign}})
	if err != nil {
		t.Fatal(err)
	}
	if len(entries) != 2 || !strings.HasPrefix(entries[1].Author, "human:") {
		t.Fatalf("published entries = %+v, want human announcement", entries)
	}
}
