package documentcmd

import (
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"

	"github.com/codyhartsook/multiplayer/internal/cli/cmdutil"
	"github.com/codyhartsook/multiplayer/internal/cli/roomctx"
	"github.com/codyhartsook/multiplayer/internal/documents"
	"github.com/codyhartsook/multiplayer/internal/room"
	"github.com/codyhartsook/multiplayer/internal/store"
)

func NewOpen(opts *cmdutil.Options) *cobra.Command {
	var (
		target targetFlags
		noOpen bool
	)
	cmd := &cobra.Command{
		Use:   "open",
		Short: "Open a generated view of this room",
		Long:  "Generates a read-only Markdown snapshot. A shell without an agent identity is treated as the local person.",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, _ []string) error {
			rc, err := roomctx.Open(cmd.Context(), opts, roomctx.Cwd())
			if err != nil {
				return err
			}
			defer rc.Close()
			r, _, err := resolve(cmd.Context(), rc, isHuman(), target)
			if err != nil {
				return err
			}
			entries, err := rc.Rooms.Entries(cmd.Context(), room.Filter{Rooms: []string{r.Key}})
			if err != nil {
				return err
			}
			authors, err := rc.Authors(cmd.Context())
			if err != nil {
				return err
			}
			participants, err := participantNames(cmd, rc, r.Key)
			if err != nil {
				return err
			}
			dir, err := documentDir(opts, r.Key)
			if err != nil {
				return err
			}
			docs, err := documents.List(dir)
			if err != nil {
				return err
			}
			path := filepath.Join(filepath.Dir(dir), "ROOM.md")
			if err := writeSnapshot(path, snapshot(r, entries, participants, documents.Names(docs), authors)); err != nil {
				return err
			}
			fmt.Fprintln(cmd.OutOrStdout(), path)
			if noOpen {
				return nil
			}
			program, args := opener(path)
			return exec.CommandContext(cmd.Context(), program, args...).Start()
		},
	}
	target.bind(cmd)
	cmd.Flags().BoolVar(&noOpen, "no-open", false, "generate and print the path without opening it")
	return cmd
}

func participantNames(cmd *cobra.Command, rc *roomctx.Context, roomKey string) ([]string, error) {
	memberships, err := rc.Rooms.Members(cmd.Context(), roomKey)
	if err != nil {
		return nil, err
	}
	var names []string
	for _, membership := range memberships {
		sess, err := rc.Store.Get(cmd.Context(), membership.SessionKey)
		if errors.Is(err, store.ErrNotFound) {
			continue
		}
		if err != nil {
			return nil, err
		}
		names = append(names, fmt.Sprintf("%s — %s", room.Display(sess), sess.Status))
	}
	return names, nil
}

func writeSnapshot(path, body string) error {
	dir := filepath.Dir(path)
	tmp, err := os.CreateTemp(dir, ".ROOM-*.md")
	if err != nil {
		return fmt.Errorf("create room snapshot: %w", err)
	}
	tmpPath := tmp.Name()
	defer os.Remove(tmpPath)
	if _, err := tmp.WriteString(body); err != nil {
		tmp.Close()
		return fmt.Errorf("write room snapshot: %w", err)
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("close room snapshot: %w", err)
	}
	if err := os.Chmod(tmpPath, 0o444); err != nil {
		return fmt.Errorf("protect room snapshot: %w", err)
	}
	if err := os.Rename(tmpPath, path); err != nil {
		return fmt.Errorf("replace room snapshot: %w", err)
	}
	return nil
}

func snapshot(r room.Room, entries []*room.Entry, participants, docs []string, authors room.Authors) string {
	var b strings.Builder
	b.WriteString("<!-- Generated by crew. Changes will be overwritten. -->\n\n")
	fmt.Fprintf(&b, "# %s · %s room\n\n", r.Name, r.Scope)
	fmt.Fprintf(&b, "Room ID: `%s`\n\n", r.Key)
	if len(participants) > 0 {
		b.WriteString("## Participants\n\n")
		for _, participant := range participants {
			fmt.Fprintf(&b, "- %s\n", participant)
		}
		b.WriteString("\n")
	}
	if len(docs) > 0 {
		b.WriteString("## Documents\n\n")
		for _, name := range docs {
			fmt.Fprintf(&b, "- [%s](documents/%s)\n", name, markdownPath(name))
		}
		b.WriteString("\n")
	}
	var open []*room.Entry
	for _, entry := range entries {
		if entry.Open() {
			open = append(open, entry)
		}
	}
	if len(open) > 0 {
		b.WriteString("## Open requests\n\n")
		for _, entry := range open {
			fmt.Fprintf(&b, "- [#%d](#%d--%s): %s — %s\n", entry.ID, entry.ID, entry.Mode, oneLine(entry.Body), authors.Name(entry.Author))
		}
		b.WriteString("\n")
	}
	b.WriteString("## Timeline\n")
	for _, entry := range entries {
		kind := string(entry.Mode)
		if entry.Resolves != 0 {
			kind = fmt.Sprintf("response to #%d", entry.Resolves)
		}
		fmt.Fprintf(&b, "\n### #%d · %s\n\n", entry.ID, kind)
		fmt.Fprintf(&b, "%s · %s\n\n", authors.Name(entry.Author), entry.CreatedAt.Local().Format("2006-01-02 15:04 MST"))
		b.WriteString(strings.TrimSpace(entry.Body))
		b.WriteString("\n")
	}
	if len(entries) == 0 {
		b.WriteString("\nNothing posted yet.\n")
	}
	return b.String()
}

func markdownPath(path string) string {
	return strings.ReplaceAll(path, " ", "%20")
}

func oneLine(s string) string { return strings.Join(strings.Fields(s), " ") }
